# Generated by Django 4.2.27 on 2026-01-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='user',
            new_name='actor',
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='entity_type',
            new_name='entity',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='hospital',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entity_id',
            field=models.CharField(max_length=50),
        ),
    ]
