# Generated by Django 4.2.27 on 2026-01-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('max_doctors', models.PositiveIntegerField(default=0)),
                ('max_receptionists', models.PositiveIntegerField(default=0)),
                ('max_medical_staff', models.PositiveIntegerField(default=0)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('footer_note', models.CharField(blank=True, help_text='Shown at bottom of consultation PDF', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='hospital_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
