# Generated by Django 4.2.27 on 2026-01-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='footer_note',
            field=models.CharField(blank=True, help_text='Shown at bottom of consultation PDF', max_length=255),
        ),
        migrations.AddField(
            model_name='hospital',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='hospital_logos/'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='max_doctors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='max_medical_staff',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='max_receptionists',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
